#!/bin/bash
#set -x

# Kill first
renice 19 $$ > /dev/null
echo 1000 > /proc/$$/oom_score_adj

cd $1

# Remove whitespaces
rename 's/ /_/g' * 2>/dev/null

cnt=$(ls *.pdf 2>/dev/null| wc -l)
[ "$cnt" -lt 1 ] && exit 1

for i in *
do
  [ -e ocr.lock ] && exit 1
  [ "$i" = "state" ] && continue
  touch ocr.lock
  echo "Importing ... 5%" > state

  file=$i
  figlet $file

  dir=$(cat /proc/sys/kernel/random/uuid)
  mkdir $dir
  mv $file $dir/
  cd $dir
  echo "Importiere ... $file" > ../state

  # From Scanner
  type=$(file --mime-type $file | cut -d' ' -f2-)
  if [ "$type" != "application/pdf" ]
  then
    convert $file Apdf.pdf
  fi
  pdftotext ${file} $dir'.txt'
  cnt=$(wc -w $dir'.txt' | awk '{print $1}')
  if [ "$cnt" -lt 30 ]
  then
    ocrmypdf -v -d -l deu --jobs 1 $file Apdf.pdf
    [ ! -e Apdf.pdf ] && convert $file Apdf.pdf
    pdftotext Apdf.pdf $dir'.txt'
  fi
  
  # Copy to Apdf.pdf if not already existing
  [ ! -e Apdf.pdf ] && cp *.pdf Apdf.pdf

  # Generate thumbnails (small x300px, medium x600px)
  convert -thumbnail x300 -background white -alpha remove Apdf.pdf[0] output_thumbnail.png 2>&1 >/dev/null

  # Add filename to search results
  echo $file >> $dir'.txt'

  cd ..
  rm ocr.lock
  echo > state
done

# Move to imported
mv *-*-*-*-* ../imported
